driver:
  name: vagrant
  customize:
    cpus: 4
    memory: 4096
  synced_folders:
    - ['.', '/home/vagrant/test']

provisioner:
  require_chef_omnibus: 11.10.4

platforms:
  - name: ubuntu-12.04
    run_list: apt::default

suites:
  - name: default
    run_list: omnibus::default
    attributes:
      omnibus:
        build_user:  vagrant
        build_dir:   /home/vagrant/test
        install_dir: /opt/test
